#
# Makefile for the Linux Wireless network device drivers.
#
obj-y += rkwlan/wifi_sys/rkwifi_sys_iface.o
obj-$(CONFIG_RTL8192CU)        += rkwlan/rtl8192cu/
obj-$(CONFIG_RTL8192DU)        += rkwlan/rtl8192du/
obj-$(CONFIG_RTL8188EU)	       += rkwlan/rtl8188eu/
obj-$(CONFIG_RTL8189ES)	       += rkwlan/rtl8189es/
obj-$(CONFIG_RTL8723AU)	       += rkwlan/rtl8723au/
obj-$(CONFIG_RTL8723BU)	       += rkwlan/rtl8723bu/
obj-$(CONFIG_RTL8812AU)	       += rkwlan/rtl8812au/
obj-$(CONFIG_RKWIFI)           += rkwlan/rkwifi/
obj-$(CONFIG_RTL8723BS)        += rkwlan/rtl8723bs/
obj-$(CONFIG_RTL8723BS_VQ0)    += rkwlan/rtl8723bs-vq0/
obj-$(CONFIG_ESP8089)   += rkwlan/esp8089/
